version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: staceynik/devops-for-programmers-project-74:latest
    ports:
      - 8080:8080
    command: npm test
    depends_on:
      - db

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

  db:
    image: postgres:latest
    environment:               
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}

