version: '3.8'
services:
  app:
    image: staceynik/devops-for-programmers-project-74:latest
    command: npm run dev

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

