version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
  caddy:
    build:
      context: ./services/caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

