version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.production
    image: staceynik/devops-for-programmers-project-74:latest
    ports:
      - ${PORT_HTTP:-8080}:8080
    command: bash -c "sleep 5 && npm test"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
      - DATABASE_PORT=${DATABASE_PORT:-5432}

  db:
    image: postgres:latest
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-postgres}
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password}
    
