version: '3.8'
services:
  app:
    build:
      context: /home/karpov/devops-for-programmers-project-74/app
      dockerfile: Dockerfile
    command: npm run dev

  caddy:
    image: caddy:latest
    ports:
      - ${PORT_HTTP:-80}:80
      - ${PORT_HTTPS:-443}:443

    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

