version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm run dev

  caddy:
    image: caddy:latest
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

