version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: staceynik/devops-for-programmers-project-74:latest
    ports:
      - 8080:8080
    command: npm test
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}

  db:
    image: postgres:latest
    ports: 
      - 5433:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

